default: true
MD013: false  # Line length
MD024: false  # Multiple headings with the same content
MD033: false  # Inline HTML
MD060: false  # Table style (optional, but convenient for compact tables)
