name: Setup Environment
description: Consolidated action for Nix and Bun environment setup.

inputs:
  github_access_token:
    description: 'GitHub token for accessing private flakes'
    required: false
  install_deps:
    description: "Whether to install Node.js dependencies"
    required: false
    default: "true"
  install_cmd:
    description: "Command to install dependencies"
    required: false
    default: "bun install --frozen-lockfile"

runs:
  using: "composite"
  steps:
    - name: Setup Nix Environment
      uses: coderbunker/modern-resume-env/.github/actions/setup-nix-env@main
      with:
        github_access_token: ${{ inputs.github_access_token }}

    - name: Setup Bun Environment
      uses: coderbunker/modern-resume-env/.github/actions/setup-bun-env@main
      with:
        install_deps: ${{ inputs.install_deps }}
        install_cmd: ${{ inputs.install_cmd }}
        github_token: ${{ inputs.github_access_token }}
