name: Setup Environment
description: Consolidated action for Nix and Bun environment setup.

inputs:
  github_access_token:
    description: 'GitHub token for accessing private flakes'
    required: false
  install_deps:
    description: "Whether to install Node.js dependencies"
    required: false
    default: "true"
  install_cmd:
    description: "Command to install dependencies"
    required: false
    default: "bun install --frozen-lockfile"
  working_directory:
    description: "Directory where the environment should be loaded from"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Nix & Load Environment
      uses: coderbunker/modern-resume-env/.github/actions/setup-nix-env@main
      with:
        github_access_token: ${{ inputs.github_access_token }}
        working_directory: ${{ inputs.working_directory }}

    - name: Check for existing Bun
      id: check-bun
      shell: bash
      run: |
        if command -v bun >/dev/null 2>&1; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
          echo "✅ Bun available via Nix or pre-installed: $(bun --version)"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup Bun (Fallback)
      if: steps.check-bun.outputs.exists != 'true'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Bun Registry & Deps
      uses: coderbunker/modern-resume-env/.github/actions/setup-bun-env@main
      with:
        install_deps: ${{ inputs.install_deps }}
        install_cmd: ${{ inputs.install_cmd }}
        github_token: ${{ inputs.github_access_token }}
        working_directory: ${{ inputs.working_directory }}
