name: Post Build Notification
description: Posts a build status comment on Pull Requests.

inputs:
  build_result:
    description: "The result of the build job (success, failure, etc.)"
    required: true
  version:
    description: "The version that was built"
    required: false
    default: "N/A"
  github_token:
    description: "GitHub Token for posting comments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Post Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { owner, repo } = context.repo;
          const buildResult = '${{ inputs.build_result }}';
          let result = '❓ **Unknown**';
          if (buildResult === 'success') result = '✅ **Success**';
          else if (buildResult === 'failure') result = '❌ **Failed**';
          else if (buildResult === 'skipped') result = '⏭️ **Skipped**';
          else if (buildResult === 'cancelled') result = '🚫 **Cancelled**';
          const version = '${{ inputs.version }}';

          // Only post on PRs
          if (context.issue.number) {
            const body = `### Build Status: ${result}\n\n` +
              `- **Workflow**: [${context.workflow}](https://github.com/${owner}/${repo}/actions/runs/${context.runId})\n` +
              `- **Version**: ${version}\n` +
              `- **Ref**: \`${context.ref}\` (\`${context.sha.substring(0, 7)}\`)\n\n` +
              `*Generated by Modern Resume CI Service*`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body
            });
          } else {
            console.log("Not a Pull Request, skipping comment.");
          }
