name: Setup Nix Shared Environment
description: Loads the shared Nix flake environment using direnv and configures the S3 binary cache.

inputs:
  s3_bucket:
    description: 'Name of the S3 bucket for the binary cache'
    required: false
    default: 'modern-resume-nix-cache'
  s3_endpoint:
    description: 'S3 API endpoint'
    required: false
    default: 's3.bhs.io.cloud.ovh.net'
  s3_public_key:
    description: 'Public key for verifying signed packages'
    required: false
    default: 'modern-resume-nix-cache-1:crKOVB7ABh6mDldfa2U9t+aUjQnx9AKeuRAE+/EkNkU='
  github_access_token:
    description: 'GitHub token for accessing private flakes'
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure Nix
      shell: bash
      run: |
        {
          echo "NIX_CONFIG<<EOF"

          # Add S3 Cache if provided (S3 comes first for priority)
          if [ -n "${{ inputs.s3_bucket }}" ] && [ -n "${{ inputs.s3_endpoint }}" ]; then
            CACHE_URL="https://${{ inputs.s3_bucket }}.${{ inputs.s3_endpoint }}"
            echo "substituters = $CACHE_URL https://cache.nixos.org"
            if [ -n "${{ inputs.s3_public_key }}" ]; then
              echo "trusted-public-keys = ${{ inputs.s3_public_key }} cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
            else
              echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
            fi
          fi

          # Add GitHub Access Token if provided
          if [ -n "${{ inputs.github_access_token }}" ]; then
            echo "access-tokens = github.com=${{ inputs.github_access_token }}"
          fi

          # Experimental features (needed for flakes)
          echo "experimental-features = nix-command flakes"

          echo "EOF"
        } >> "$GITHUB_ENV"

    - name: Load Environment via Direnv
      shell: bash
      run: |
        # Add Nix to PATH immediately
        export PATH="/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/usr/local/bin:$PATH"

        if ! command -v nix >/dev/null 2>&1; then
          echo "::error::Nix not found in PATH ($PATH)."
          exit 1
        fi

        # Install direnv if not present
        if ! command -v direnv >/dev/null 2>&1; then
          echo "Installing direnv..."
          nix profile install nixpkgs#direnv --extra-experimental-features "nix-command flakes"
          export PATH="$HOME/.nix-profile/bin:$PATH"
        fi

        # Allow direnv to load the flake
        direnv allow

        # Capture the environment JSON
        # Note: direnv will automatically use the NIX_CONFIG we set earlier
        ENV_JSON=$(direnv export json)

        if [ -n "$ENV_JSON" ] && [ "$ENV_JSON" != "{}" ]; then
          # Export non-PATH variables
          echo "$ENV_JSON" | jq -r 'to_entries | .[] | select(.key != "PATH") | "\(.key)<<EOF\n\(.value)\nEOF"' >> "$GITHUB_ENV"

          # Export PATH split into individual lines
          echo "$ENV_JSON" | jq -r 'select(.PATH != null) | .PATH | split(":") | .[]' >> "$GITHUB_PATH"
          echo "Shared environment successfully loaded from flake."
        else
          echo "::error::direnv failed to export environment variables."
          exit 1
        fi
