name: Repolinter Self-Lint

on:
  push:
    branches: ["main", "develop"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/repolinter.yml
    secrets: inherit
